---
permalink: deploy/prerequisites.html 
sidebar: sidebar 
keywords: ONTAP tools,Storage Replication Adapter 
summary: Avant de déployer les ONTAP tools for VMware vSphere, vous devez connaître les exigences d’espace pour le package de déploiement et certaines exigences de base du système hôte. 
---
= Exigences et limites de configuration des ONTAP tools for VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de déployer les ONTAP tools for VMware vSphere, vous devez connaître les exigences d’espace pour le package de déploiement et certaines exigences de base du système hôte.

Vous pouvez utiliser les ONTAP tools for VMware vSphere avec VMware vCenter Server Virtual Appliance (vCSA).  Vous devez déployer les ONTAP tools for VMware vSphere sur un client vSphere pris en charge qui inclut le système ESXi.



== Configuration requise

* *Exigences d'espace du package d'installation par nœud*
+
** 15 Go pour les installations à provisionnement léger
** 348 Go pour les installations à provisionnement épais


* *Exigences de dimensionnement du système hôte* La mémoire recommandée en fonction de la taille du déploiement est indiquée dans le tableau ci-dessous.  Pour déployer la haute disponibilité (HA), vous aurez besoin de trois fois la taille de l'appliance spécifiée dans le tableau.


|===


| *Type de déploiement* | *CPU par nœud* | *Mémoire (Go) par nœud* | *Espace disque (Go) provisionné en épaisseur par nœud* 


| Petit | 9 | 18 | 350 


| Moyen | 13 | 26 | 350 


| REMARQUE importante : le déploiement à grande échelle concerne uniquement la configuration HA. | 17 | 34 | 350 
|===

NOTE: Lorsque la sauvegarde est activée, chaque cluster d’outils ONTAP a besoin de 50 Go d’espace supplémentaires sur la banque de données où les machines virtuelles sont déployées.  Par conséquent, le non-HA nécessite 400 Go et le HA nécessite 1 100 Go d’espace au total.



== Exigences minimales de stockage et d'application

|===
| Stockage, hôte et applications | Exigences de version 


| ONTAP | 9.14.1, 9.15.1, 9.16.0, 9.16.1 et 9.16.1P3 FAS, ASA série A, ASA série C, AFF série A, AFF série C et ASA r2. 


| Les outils ONTAP prennent en charge les hôtes ESXi | 7.0.3 et versions ultérieures 


| Outils ONTAP pris en charge par vCenter Server | 7.0U3 et versions ultérieures 


| Fournisseur VASA | 3,0 


| Demande OVA | 10,4 


| Hôte ESXi pour déployer la machine virtuelle des outils ONTAP | 7.0U3 et 8.0U3 


| vCenter Server pour déployer la machine virtuelle des outils ONTAP | 7.0 et 8.0 
|===

NOTE: À partir des ONTAP tools for VMware vSphere 10.4, le matériel de la machine virtuelle passe de la version 10 à la version 17.

L'outil de matrice d'interopérabilité (IMT) contient les informations les plus récentes sur les versions prises en charge d' ONTAP, de vCenter Server, des hôtes ESXi et des applications plug-in.

https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["Outil de matrice d'interopérabilité"^]



== Exigences portuaires

Le tableau suivant présente les ports réseau utilisés par NetApp et leurs fonctions. Il existe trois types de ports différents :

* Ports externes : ces ports sont accessibles depuis l’extérieur du cluster ou du nœud Kubernetes.  Ils permettent aux services de communiquer avec des réseaux ou des utilisateurs externes, permettant ainsi l'intégration avec des systèmes situés en dehors de l'environnement du cluster.
* Ports inter-nœuds : ces ports permettent la communication entre les nœuds au sein du cluster Kubernetes.  Ils sont nécessaires pour les tâches en cluster telles que le partage de données et le travail collaboratif.  Pour les déploiements à nœud unique, les ports inter-nœuds sont utilisés uniquement au sein du nœud et n'ont pas besoin d'accès externe.  Les ports inter-nœuds peuvent accepter le trafic provenant de l'extérieur du cluster.  Bloquez l'accès Internet aux ports inter-nœuds à l'aide de règles de pare-feu.
* Ports internes : ces ports communiquent au sein du cluster Kubernetes à l’aide d’adresses ClusterIP.  Elles ne sont pas exposées de l'extérieur et n'ont pas besoin d'être ajoutées aux règles du pare-feu.



NOTE: Assurez-vous que tous les nœuds des outils ONTAP résident sur le même sous-réseau pour maintenir une communication ininterrompue entre eux.


|===
| *Nom du service/composant* | *Port* | *Protocole* | *Type de port* | *Description* 


| ntv-gateway-svc (LB) | 443, 8443 | TCP | Externe | Port de transit pour les communications entrantes du service fournisseur VASA. Le certificat auto-signé du fournisseur VASA et le certificat CA personnalisé sont hébergés sur ce port. 


| SSH | 22 | TCP | Externe | Secure Shell pour la connexion à un serveur distant et l'exécution de commandes. 


| serveur rke2 | 9345 | TCP | Inter-nœud | API de supervision RKE2 (Restriction aux réseaux de confiance). 


| kube-apiserver | 6443 | TCP | Inter-nœud | Port du serveur API Kubernetes (à limiter aux réseaux de confiance). 


| rpcbind/portmapper | 111 | TCP/UDP | Inter-nœud | Utilisé pour la communication RPC entre les services. 


| coredns (DNS) | 53 | TCP/UDP | Inter-nœud | Service DNS (Domain Name System) pour la résolution de noms au sein du cluster. 


| NTP | 123 | UDP | Inter-nœud | Protocole NTP (Network Time Protocol) pour la synchronisation de l'heure. 


| etcd | 2379, 2380, 2381 | TCP | Inter-nœud | Système de stockage clé-valeur pour les données de cluster. 


| kube-vip | 2112 | TCP | Inter-nœud | Port du serveur API Kubernetes. 


| kubelet | 10248, 10250 | TCP | Inter-nœud | Composant Kubernetes 


| contrôleur kube | 10257 | TCP | Inter-nœud | Composant Kubernetes 


| contrôleur cloud | 10258 | TCP | Inter-nœud | Composant Kubernetes 


| kube-scheduler | 10259 | TCP | Inter-nœud | Composant Kubernetes 


| kube-proxy | 10249, 10256 | TCP | Inter-nœud | Composant Kubernetes 


| nœud calico | 9091, 9099 | TCP | Inter-nœud | Composant réseau Calico. 


| conteneur | 10010 | TCP | Inter-nœud | Service démon du conteneur. 


| VXLAN (Flannel) | 8472 | UDP | Inter-nœud | Réseau superposé pour la communication entre les pods. 
|===

NOTE: Pour les déploiements HA, assurez-vous que le port UDP 8472 est ouvert entre tous les nœuds.  Ce port permet la communication entre les pods au sein des nœuds ; son blocage interrompra la mise en réseau entre les nœuds.



== Limites de configuration pour déployer les ONTAP tools for VMware vSphere

Vous pouvez utiliser le tableau suivant comme guide pour configurer les ONTAP tools for VMware vSphere.

|===


| *Déploiement* | *Taper* | *Nombre de vVols* | *Nombre d'hôtes* 


| Non-HA | Petit (S) | ~12 000 | 32 


| Non-HA | Moyen (M) | ~24K | 64 


| Haute disponibilité | Petit (S) | ~24K | 64 


| Haute disponibilité | Moyen (M) | ~50 000 | 128 


| Haute disponibilité | Grand (L) | ~100 000 | 256 [REMARQUE] Le nombre d'hôtes dans le tableau indique le nombre total d'hôtes provenant de plusieurs vCenter. 
|===


== ONTAP tools for VMware vSphere - Adaptateur de réplication de stockage (SRA)

Le tableau suivant indique les nombres pris en charge par instance VMware Live Site Recovery à l'aide des ONTAP tools for VMware vSphere.

|===
| *Taille du déploiement vCenter* | *Petit* | *Moyen* 


| Nombre total de machines virtuelles configurées pour la protection à l'aide de la réplication basée sur une baie | 2000 | 5000 


| Nombre total de groupes de protection de réplication basés sur des baies | 250 | 250 


| Nombre total de groupes de protection par plan de récupération | 50 | 50 


| Nombre de banques de données répliquées | 255 | 255 


| Nombre de machines virtuelles | 4000 | 7000 
|===
Le tableau suivant indique le nombre de VMware Live Site Recovery et les ONTAP tools for VMware vSphere .

|===


| *Nombre d'instances VMware Live Site Recovery* | * Taille du déploiement des outils ONTAP * 


| Jusqu'à 4 | Petit 


| 4 à 8 | Moyen 


| Plus de 8 | Grand 
|===
Pour plus d'informations, consultez  https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/overview/site-recovery-manager-system-requirements/operational-limits-of-site-recovery-manager.html["Limites opérationnelles de VMware Live Site Recovery"] .
