---
permalink: protect/configure-array-manager.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez configurer l"adaptateur de réplication de stockage (SRA) à l"aide de l"assistant Array Manager de VMware Live Site Recovery pour activer les interactions entre VMware Live Site Recovery et les machines virtuelles de stockage (SVM).' 
---
= Configurer SRA à l'aide du gestionnaire de baies
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez configurer l'adaptateur de réplication de stockage (SRA) à l'aide de l'assistant Array Manager de VMware Live Site Recovery pour activer les interactions entre VMware Live Site Recovery et les machines virtuelles de stockage (SVM).

.Avant de commencer
* Vous devez avoir associé les sites protégés et les sites de récupération dans VMware Live Site Recovery.
* Vous devez avoir configuré votre stockage intégré avant de configurer le gestionnaire de baies.
* Vous devez avoir configuré et répliqué les relations SnapMirror entre les sites protégés et les sites de récupération.
* Vous devez avoir activé les LIF de gestion SVM pour activer la multilocation.


SRA prend en charge la gestion au niveau du cluster et la gestion au niveau SVM.  Si vous ajoutez du stockage au niveau du cluster, vous pouvez alors découvrir et effectuer des opérations sur toutes les SVM du cluster.  Si vous ajoutez du stockage au niveau SVM, vous ne pouvez gérer que ce SVM spécifique.

.Étapes
. Dans VMware Live Site Recovery, sélectionnez *Gestionnaires de baies* > *Ajouter un gestionnaire de baies*.
. Saisissez les informations suivantes pour décrire la baie dans VMware Live Site Recovery :
+
.. Saisissez un nom pour identifier le gestionnaire de tableau dans le champ *Nom d'affichage*.
.. Dans le champ *Type SRA*, sélectionnez *Adaptateur de réplication de stockage NetApp pour ONTAP*.
.. Saisissez les informations pour vous connecter au cluster ou au SVM :
+
*** Si vous vous connectez à un cluster, vous devez saisir le LIF de gestion du cluster.
*** Si vous vous connectez directement à un SVM, vous devez saisir l'adresse IP du LIF de gestion du SVM.
+

NOTE: Lors de la configuration du gestionnaire de baies, vous devez utiliser la même connexion (adresse IP) pour le système de stockage qui a été utilisé pour intégrer le système de stockage dans les ONTAP tools for VMware vSphere.  Par exemple, si la configuration du gestionnaire de baies est limitée à SVM, le stockage sous les ONTAP tools for VMware vSphere doit être ajouté au niveau SVM.



.. Si vous vous connectez à un cluster, spécifiez le nom de la SVM dans le champ *Nom de la SVM* ou laissez-le vide pour gérer toutes les SVM du cluster.
.. Saisissez les volumes à découvrir dans le champ *Liste des volumes inclus*.
+
Vous pouvez entrer le volume source sur le site protégé et le volume de destination répliqué sur le site de récupération.

+
Par exemple, si vous souhaitez découvrir le volume src_vol1 qui se trouve dans une relation SnapMirror avec le volume dst_vol1, vous devez spécifier src_vol1 dans le champ site protégé et dst_vol1 dans le champ site de récupération.

.. *(Facultatif)* Saisissez les volumes à exclure de la découverte dans le champ *Liste d'exclusion de volumes*.
+
Vous pouvez entrer le volume source sur le site protégé et le volume de destination répliqué sur le site de récupération.

+
Par exemple, si vous souhaitez exclure le volume _src_vol1_ qui se trouve dans une relation SnapMirror avec le volume _dst_vol1_, vous devez spécifier _src_vol1_ dans le champ de site protégé et _dst_vol1_ dans le champ de site de récupération.



. Sélectionnez *Suivant*.
. Vérifiez que le tableau est détecté et affiché en bas de la fenêtre Ajouter un gestionnaire de tableaux et sélectionnez *Terminer*.


Vous pouvez suivre les mêmes étapes pour le site de récupération en utilisant les adresses IP et les informations d’identification de gestion SVM appropriées.  Sur l'écran Activer les paires de baies de l'assistant Ajouter un gestionnaire de baies, vous devez vérifier que la paire de baies correcte est sélectionnée et qu'elle s'affiche comme prête à être activée.
