---
permalink: protect/map-network.html 
sidebar: sidebar 
keywords:  
summary: Vous devez mapper vos réseaux sur le site protégé et le site de récupération pour permettre la communication entre eux. 
---
= Configurer les mappages réseau
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez configurer vos mappages de ressources tels que les réseaux de machines virtuelles, les hôtes ESXi et les dossiers sur les deux sites pour permettre le mappage de chaque ressource du site protégé vers la ressource appropriée sur le site de récupération.

Vous devez effectuer les configurations de ressources suivantes :

* Cartographies de réseau
* Mappages de dossiers
* Cartographie des ressources
* Magasins de données d'espace réservé


.Avant de commencer
Vous devez avoir connecté les sites protégés et de récupération.

.Étapes
. Connectez-vous à vCenter Server et sélectionnez *Site Recovery* > *Sites*.
. Sélectionnez votre site protégé et sélectionnez *Gérer*.
. Sélectionnez *Mappages réseau* > *Nouveau* dans l’onglet Gérer pour créer un nouveau mappage réseau.
. Dans l’assistant de création de mappage réseau, procédez comme suit :
+
.. Sélectionnez *Préparer automatiquement les mappages pour les réseaux avec des noms correspondants* et sélectionnez *Suivant*.
.. Sélectionnez les objets du centre de données requis pour les sites protégés et de récupération et sélectionnez *Ajouter des mappages*.
.. Sélectionnez *Suivant* une fois les mappages créés avec succès.
.. Sélectionnez l’objet utilisé précédemment pour créer le mappage inversé, puis sélectionnez *Terminer*.




.Résultat
La page Mappages réseau affiche les ressources du site protégé et les ressources du site de récupération.  Vous pouvez suivre les mêmes étapes pour d’autres réseaux de votre environnement.
