---
permalink: protect/map-resource.html 
sidebar: sidebar 
keywords:  
summary: Vous devez mapper vos ressources sur le site protégé et le site de récupération afin que les machines virtuelles soient configurées pour basculer vers un groupe d’hôtes ou vers l’autre. 
---
= Configurer les mappages de ressources
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez mapper vos ressources sur le site protégé et le site de récupération afin que les machines virtuelles soient configurées pour basculer vers un groupe d’hôtes ou vers l’autre.

.Avant de commencer
Vous devez avoir connecté les sites protégés et de récupération.


NOTE: Dans VMware Live Site Recovery, les ressources peuvent être des pools de ressources, des hôtes ESXi ou des clusters vSphere.

.Étapes
. Connectez-vous à vCenter Server et sélectionnez *Site Recovery* > *Sites*.
. Sélectionnez votre site protégé et sélectionnez *Gérer*.
. Sélectionnez *Mappages de ressources* > *Nouveau* dans l’onglet Gérer pour créer un nouveau mappage de ressources.
. Dans l’assistant de création de mappage de ressources, procédez comme suit :
+
.. Sélectionnez *Préparer automatiquement les mappages pour les ressources avec des noms correspondants* et sélectionnez *Suivant*.
.. Sélectionnez les objets du centre de données requis pour les sites protégés et de récupération et sélectionnez *Ajouter des mappages*.
.. Sélectionnez *Suivant* une fois les mappages créés avec succès.
.. Sélectionnez l'objet utilisé précédemment pour créer le mappage inversé, puis sélectionnez *Terminer*.




.Résultat
La page Mappages de ressources affiche les ressources du site protégé et les ressources du site de récupération.  Vous pouvez suivre les mêmes étapes pour d’autres réseaux de votre environnement.
