---
permalink: protect/update-credentials.html 
sidebar: sidebar 
keywords: SRA credentials, updating 
summary: 'Pour que VMware Live Site Recovery communique avec SRA, vous devez mettre à jour les informations d"identification SRA sur le serveur VMware Live Site Recovery si vous avez modifié les informations d"identification.' 
---
= Mettre à jour les informations d'identification SRA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour que VMware Live Site Recovery communique avec SRA, vous devez mettre à jour les informations d'identification SRA sur le serveur VMware Live Site Recovery si vous avez modifié les informations d'identification.

.Avant de commencer
Vous devriez avoir exécuté les étapes mentionnées dans le sujetlink:../protect/configure-on-srm-appliance.html["Configuration de SRA sur le dispositif VMware Live Site Recovery"] .

.Étapes
. Exécutez les commandes suivantes pour supprimer le nom d'utilisateur et le mot de passe des outils ONTAP mis en cache dans le dossier de la machine VMware Live Site Recovery :
+
.. `sudo su <enter root password>`
.. `docker ps`
.. `docker exec -it <container_id> sh`
.. `cd conf/`
.. `rm -rf *`


. Exécutez la commande Perl pour configurer SRA avec les nouvelles informations d’identification :
+
.. `cd ..`
.. `perl command.pl -I --otv-ip <OTV_IP>:8443 --otv-username <OTV_ADMIN_USERNAME> --otv-password <OTV_ADMIN_PASSWORD> --vcenter-guid <VCENTER_GUID>`Vous devez avoir une seule apostrophe autour de la valeur du mot de passe.
+
Un message de réussite confirmant que les informations d'identification de stockage sont enregistrées s'affiche.  SRA peut communiquer avec le serveur SRA en utilisant l'adresse IP, le port et les informations d'identification fournis.




