---
permalink: manage/change-manager-password.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez modifier le mot de passe administrateur à l"aide du gestionnaire d"outils ONTAP .' 
---
= Modifier le mot de passe du gestionnaire d'outils ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez modifier le mot de passe administrateur à l'aide du gestionnaire d'outils ONTAP .

.Étapes
. Lancez le gestionnaire d’outils ONTAP à partir d’un navigateur Web : `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Connectez-vous avec les informations d’identification d’administrateur des ONTAP tools for VMware vSphere que vous avez fournies lors du déploiement.
. Sélectionnez l'icône *administrateur* dans le coin supérieur droit de l'écran et sélectionnez *Modifier le mot de passe*.
. Dans la fenêtre contextuelle de modification du mot de passe, saisissez l'ancien mot de passe et les détails du nouveau mot de passe.  La contrainte de modification du mot de passe est affichée sur l'écran de l'interface utilisateur.
. Sélectionnez *Modifier* pour appliquer les modifications.

