---
permalink: manage/update-vcenter-credentials.html 
sidebar: sidebar 
keywords:  
summary: Vous pouvez mettre à jour les informations d’identification de vCenter Server et ONTAP à l’aide de la console de maintenance. 
---
= Mettre à jour les informations d'identification de vCenter Server et ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez mettre à jour l’instance vCenter Server et les informations d’identification ONTAP à l’aide de la console de maintenance.

.Avant de commencer
Vous devez disposer des informations de connexion de l'utilisateur de maintenance.

*À propos de cette tâche*

Si vous avez modifié les informations d’identification de vCenter Server, ONTAP ou Data LIF après le déploiement, vous devez mettre à jour les informations d’identification à l’aide de cette procédure.

.Étapes
. Depuis vCenter Server, ouvrez une console sur VASA Provider.
. Connectez-vous en tant qu'utilisateur de maintenance.
. Entrer `2` pour sélectionner le menu de configuration du système.
. Entrer `9` pour modifier les informations d'identification ONTAP .
. Entrer `10` pour modifier les informations d'identification de vCenter.

